---
add: #You can add as many recipes as you want
  casqueura: #Here you can put the name you want to organize your config
    recipe: ["302","0"] #["ID","META"]Item to cook
    result: ["388","0"] #["ID","META"]Cooking result
  plastronura:
    recipe: ["303","0"]
    result: ["388","0"]
  jambiereura:
    recipe: ["304","0"]
    result: ["388","0"]   
  botteura:
    recipe: ["305","0"]
    result: ["388","0"]
...
