---
#Exchange plugin by HiroTeam | Plugin de Bourse par la HiroTeam
#██╗░░██╗██╗██████╗░░█████╗░████████╗███████╗░█████╗░███╗░░░███╗
#██║░░██║██║██╔══██╗██╔══██╗╚══██╔══╝██╔════╝██╔══██╗████╗░████║
#███████║██║██████╔╝██║░░██║░░░██║░░░█████╗░░███████║██╔████╔██║
#██╔══██║██║██╔══██╗██║░░██║░░░██║░░░██╔══╝░░██╔══██║██║╚██╔╝██║
#██║░░██║██║██║░░██║╚█████╔╝░░░██║░░░███████╗██║░░██║██║░╚═╝░██║
#╚═╝░░╚═╝╚═╝╚═╝░░╚═╝░╚════╝░░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝
#description:
#ENG: It is a purse plugin which allows you to change the price of items relative to the number of items purchased according to a time, the uptime !
#FRA: C'est un plugin de bourse qui permet de changer le prix des items par rapport au nombre d'item acheté selon un temps, le uptime !

add: #You can add as many recipes as you want | Vous pouvez ajouter autant de recette que vous voulez
  casqueura: #Here you can put the name you want to organize your config | Vous pouvez mettre le nom que vous souhaitez pour vous organiser
    recipe: ["302","0"] #["ID","META"]Item to cook | Item à cuire
    result: ["388","0"] #["ID","META"]Cooking result | Resultat 
  plastronura:
    recipe: ["303","0"]
    result: ["388","0"]
  jambiereura:
    recipe: ["304","0"]
    result: ["388","0"]   
  botteura:
    recipe: ["305","0"]
    result: ["388","0"]
...
